theme: jekyll-theme-minimal
title: Jason Choi
logo: /assets/headshot_circle.png
description: Hello! I'm an Economics grad from NYU with 2 years of experience as a Marketing Coordinator + Analyst at a Creative Agency. This site serves as my current portfolio, featuring a few data-driven projects that I've worked on.
markdown: GFM
