theme: jekyll-theme-minimal
title: Jason Choi
logo: /assets/headshot_circle_0.png
description: Hello! I'm Jason, a Data Analyst skilled in dataset management, dashboard reporting, and business intelligence. I'm a collaborative team player passionate about delivering actionable insights with a keen eye for visual appeal. Let's navigate from data to impact together.
markdown: GFM
