theme: jekyll-theme-minimal
title: Jason Choi
logo: /assets/headshot_circle_0.png
description: Hi, I'm Jason, a Data Research Analyst skilled in simplifying data for actionable insights. With a sharp eye for detail, I transform vast datasets into clear trends that drive decision-making and innovation. Let's navigate from data to impact together.
markdown: GFM
