theme: jekyll-theme-minimal
title: Jason Choi
logo: /assets/headshot_circle_1.png
description: Hi! I'm an Economics grad from NYU with 2 years as a Marketing Coordinator + Analyst at a Creative Agency. This site features a few of my recent data-driven projects.
email: jasonchoiprod@gmail.com 
markdown: GFM
header_navigation:
- title: Contact
  url: jasonchoiprod@gmail.com 
