theme: jekyll-theme-minimal
title: Jason Choi
email: jasonchoiprod@gmail.com
logo: /assets/headshot_circle_1.png
description: Welcome! I'm an Economics graduate from NYU with two years of experience as an analyst at a Multicultural Creative Agency. This site is my portfolio, featuring recent projects that I've worked on.
markdown: GFM
